import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getUsers } from '@/utils/dataUtils';

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedInUserId = 1;
  const users = await getUsers();

  const filteredUsers = users.filter(user => user.id !== loggedInUserId);

  return (
    <html lang="en">
      <body>
        <div className="antialiased bg-gray-50 dark:bg-gray-900">
          <Navbar />
          <Sidebar users={filteredUsers} />

          <main className="p-4 md:ml-80 min-h-screen pt-20">
            <div className="flex flex-col justify-between">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
